name: notes
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  dio: ^5.9.0
  image_picker: ^1.2.0
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/image/


  fonts:
     - family: Tajawal
       fonts:
         - asset: assets/fonts/Tajawal-Medium.ttf
